"""empty message

Revision ID: ba7ebfeb70b9
Revises: df6965aced80
Create Date: 2024-09-29 10:54:58.500674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7ebfeb70b9'
down_revision: Union[str, None] = 'df6965aced80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_id'), 'director', ['id'], unique=False)
    op.create_index(op.f('ix_director_name'), 'director', ['name'], unique=True)
    op.create_index(op.f('ix_director_slug'), 'director', ['slug'], unique=True)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_index(op.f('ix_genre_slug'), 'genre', ['slug'], unique=True)
    op.create_index(op.f('ix_genre_title'), 'genre', ['title'], unique=True)
    op.create_table('movie_director',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    op.create_table('movie_genre',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.add_column('movie', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('movie', sa.Column('release', sa.DateTime(), nullable=False))
    op.drop_index('ix_movie_name', table_name='movie')
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=True)
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    op.drop_index('ix_screenshot_image_url', table_name='screenshot')
    op.create_index(op.f('ix_screenshot_movie_id'), 'screenshot', ['movie_id'], unique=False)
    op.create_unique_constraint(None, 'screenshot', ['image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screenshot', type_='unique')
    op.drop_index(op.f('ix_screenshot_movie_id'), table_name='screenshot')
    op.create_index('ix_screenshot_image_url', 'screenshot', ['image_url'], unique=False)
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.create_index('ix_movie_name', 'movie', ['name'], unique=False)
    op.drop_column('movie', 'release')
    op.drop_column('movie', 'slug')
    op.drop_table('movie_genre')
    op.drop_table('movie_director')
    op.drop_index(op.f('ix_genre_title'), table_name='genre')
    op.drop_index(op.f('ix_genre_slug'), table_name='genre')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_director_slug'), table_name='director')
    op.drop_index(op.f('ix_director_name'), table_name='director')
    op.drop_index(op.f('ix_director_id'), table_name='director')
    op.drop_table('director')
    # ### end Alembic commands ###
